import './globals.css'
import { Poppins } from 'next/font/google'
import Header from '@/components/header'
import Footer from '@/components/footer'
import { CartProvider } from '../context/cartContext';

const poppins = Poppins({ subsets: ['latin'],weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <CartProvider>
      <body className={`${poppins.className} dark:bg-gray-900 dark:text-white`}>
        <Header />
        {children}
        <Footer />
        </body>
        </CartProvider>

      
    </html>
  )
}
